title: Notes & Stuff
description: My Personal Stack Problems
author: Nicolas Landier
github: https://github.com/landier
about: 
disqus_shortname: nlandier
google_analytics: UA-150453836-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-facebook
#      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/landier"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/landier/"
#    - icon: fa-stack-exchange
#      link: "#"
    - icon: fa-github
      link: "https://github.com/landier"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
#    - text: About Me
#      url: /about/
#    - text: My Projects
#      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://nicolas.landier.org"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
